# -*- coding: utf-8 -*-
"""MiniLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIFrcIfjQytWTDvLoKMfh6fXOnPjVJ5r
"""

!pip install sentence-transformers

import pandas as pd
import numpy as np

from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files

print("Envie o Excel")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

df_raw = pd.read_excel(filename)
df_raw['Classificação'] = df_raw['Classificação'].ffill()

colunas_meses = [c for c in df_raw.columns if isinstance(c, str) and c[:4].isdigit()]

df = (
    df_raw
    .groupby(['Classificação', 'Título'])[colunas_meses]
    .sum()
    .reset_index()
)

df['total_emprestimos'] = df[colunas_meses].sum(axis=1)

df['cdd'] = df['Classificação'].astype(str)
df['area'] = df['cdd'].str.extract(r'(\d{3})').fillna('')

df['Título'] = df['Título'].fillna('')

modelo = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

embeddings = modelo.encode(df['Título'].tolist(), show_progress_bar=True)
matriz_semantica = cosine_similarity(embeddings)

df['log_emp'] = np.log1p(df['total_emprestimos'])
df['score_emp'] = MinMaxScaler().fit_transform(df[['log_emp']])

cdd_list = df['cdd'].astype(str).values

def sim_cdd(idx):
    a = cdd_list[idx]
    sims = []
    for b in cdd_list:
        if a == b:
            sims.append(1.0)
        elif a[:3] == b[:3]:
            sims.append(0.8)
        elif a[:2] == b[:2]:
            sims.append(0.5)
        elif a[:1] == b[:1]:
            sims.append(0.2)
        else:
            sims.append(0.0)

    return np.array(sims)

def melhor_referencia(busca):

    mask = df['Título'].str.upper().str.contains(
        busca.upper(),
        na=False
    )

    matches = df[mask]

    if matches.empty:
        return None

    return matches['total_emprestimos'].idxmax()

def recomendar(busca, top_n=5):

    idx = melhor_referencia(busca)

    if idx is None:
        print("Livro não encontrado")
        return None

    print("\n==============================")
    print(" REFERÊNCIA:")
    print(df.loc[idx, 'Título'])
    print("==============================")

    scores = (
        0.30 * matriz_semantica[idx] +
        0.30 * sim_cdd(idx) +
        0.40 * df['score_emp'].values
    )

    ranking = np.argsort(scores)[::-1]
    ranking = [i for i in ranking if i != idx][:top_n]

    for i, r in enumerate(ranking, 1):
        print(
            f"{i}. "
            f"{df.loc[r, 'Título']} "
            f"(CDD {df.loc[r, 'cdd']})"
        )

    return ranking

def avaliar(termos, top_n=5):
    resultados = []
    for termo in termos:
        idx = melhor_referencia(termo)
        if idx is None:
            continue
        ref = df.loc[idx]

        scores = matriz_semantica[idx]

        ranking = np.argsort(scores)[::-1]
        ranking = [i for i in ranking if i != idx][:top_n]

        relevantes = set(
            df[df['cdd'] == ref['cdd']].index
        )

        if idx in relevantes:
            relevantes.remove(idx)

        TP = len(set(ranking) & relevantes)

        FP = top_n - TP

        total_relevantes_acervo = len(relevantes)

        FN = max(
            0,
            total_relevantes_acervo - TP
        )

        N_total = len(df) - 1

        TN = (
            N_total
            - TP
            - FP
            - FN
        )

        accuracy = (
            (TP + TN) / N_total
            if N_total > 0
            else 0
        )

        precision = (
            TP / top_n
            if top_n > 0
            else 0
        )

        recall = (
            TP / total_relevantes_acervo
            if total_relevantes_acervo > 0
            else 0
        )

        f1 = (
            (2 * precision * recall)
            / (precision + recall)
            if (precision + recall) > 0
            else 0
        )

        print("\n" + "=" * 90)
        print(f"Referência: {ref['Título']}")
        print(f"CDD: {ref['cdd']}")
        print("=" * 90)

        print(
            f"{'#':<3} "
            f"{'Livro':<55} "
            f"{'CDD':<10} "
            f"{'Relevante'}"
        )

        print("-" * 90)

        for pos, r in enumerate(ranking, 1):

            titulo = str(df.loc[r, 'Título'])[:53]
            cdd = df.loc[r, 'cdd']

            rel = (
                "SIM"
                if r in relevantes
                else "NÃO"
            )

            print(
                f"{pos:<3} "
                f"{titulo:<55} "
                f"{cdd:<10} "
                f"{rel}"
            )

        print("\nMÉTRICAS")
        print(
            f"Accuracy  : {accuracy:.4f}"
        )
        print(
            f"Precision : {precision:.4f}"
        )
        print(
            f"Recall    : {recall:.4f}"
        )
        print(
            f"F1-Score  : {f1:.4f}"
        )

        for rank, r in enumerate(ranking, 1):

            resultados.append({

                "Livro_Alvo":
                    ref['Título'],

                "CDD_Alvo":
                    ref['cdd'],

                "Rank_Rec":
                    rank,

                "Livro_Recomendado":
                    df.loc[r, 'Título'],

                "CDD_Recomendado":
                    df.loc[r, 'cdd'],

                "Acerto_CDD":
                    (
                        "Sim"
                        if r in relevantes
                        else "Não"
                    ),

                "Score_Similaridade_Texto":
                    round(scores[r], 4),

                "Acuracia_Top5":
                    round(accuracy, 6),

                "Precisao_Top5":
                    round(precision, 6),

                "Recall_Top5":
                    round(recall, 6),

                "F1_Score_Top5":
                    round(f1, 6)

            })

    df_res = pd.DataFrame(resultados)

    print("\n" + "=" * 90)
    print("MÉDIA GERAL")
    print("=" * 90)

    print(
        f"Acurácia Média : "
        f"{df_res['Acuracia_Top5'].mean():.4f}"
    )

    print(
        f"Precisão Média : "
        f"{df_res['Precisao_Top5'].mean():.4f}"
    )

    print(
        f"Recall Médio   : "
        f"{df_res['Recall_Top5'].mean():.4f}"
    )

    print(
        f"F1 Médio       : "
        f"{df_res['F1_Score_Top5'].mean():.4f}"
    )

    print(
        f"Score Médio    : "
        f"{df_res['Score_Similaridade_Texto'].mean():.4f}"
    )

    print("=" * 90)

    df_res.to_excel(
        "metricas_minilm.xlsx",
        index=False
    )

    print(
        "\nArquivo salvo: "
        "metricas_minilm.xlsx"
    )

    return df_res
termos = [
    "Cálculo - 3. ed. / 2014",
    "Fundamentos de física - 9. ed. / 2012",
    "Fundamentos de matemática elementar: 1 : conjuntos, funções - 9. ed. / 2013",
    "Lógica para computação / 2006",
    "Álgebra linear com aplicações - 10. ed. / 2012",
    "Resistência dos materiais - 7. ed. / 2010",
    "Ciência e engenharia de materiais: uma introdução - 8. ed. / 2012",
    "Fundamentos da termodinâmica / 2013",
    "Equações diferenciais - 3. ed. / 2001",
    "Termodinâmica - 7. ed. / 2013"
]

df_metricas = avaliar(termos)